### ISSUE TITLE
Default I2S output to different GPIO pins?

### ISSUE THREAD

**Issue by colonelwatch** [raspberrypi/pico-extras#3]
When I was building [usb_sound_card](https://github.com/raspberrypi/pico-playground/tree/master/apps/usb_sound_card) from the pico-playground repo, I had to define a different set of GPIO pins in the CMakeLists.txt file because GP25 was not exposed on the Raspberry Pi Pico.

https://github.com/raspberrypi/pico-extras/blob/f5c7be9a86e3131cd13d2cc3493b84b23676f8c4/src/rp2_common/pico_audio_i2s/include/pico/audio_i2s.h#L99-L107

So, a default `PICO_AUDIO_I2S_CLOCK_PIN_BASE` of 25 doesn't sound great. Shouldn't this be a different pin? In my case, I set `PICO_AUDIO_I2S_CLOCK_PIN_BASE` to 26 and `PICO_AUDIO_I2S_DATA_PIN` to 28. This leaves the WS signal, which then is 27 because that is `PICO_AUDIO_I2S_CLOCK_PIN_BASE+1`. All of these pins are exposed on the Pico.

**Comment by kilograham** [comment]
fixed
