### ISSUE TITLE
Broken links in ```src/common/pico_scanvideo/README.adoc```

### ISSUE THREAD

**Issue by sokratisvas** [raspberrypi/pico-extras#44]
Hi,

Some links in [README.adoc](https://github.com/raspberrypi/pico-extras/blob/master/src/common/pico_scanvideo/README.adoc) seem to be broken:

1\. Line 9 ```https://github.com/raspberrypi/pico-playground/scanvideo/mandelbrot[mandelbrot]```
2\. Line 64 ```https://github.com/raspberrypi/pico-playground/scanvideo/svideo_minimal[scanvideo_minimal]```

**Comment by kilograham** [comment]
mergeed
