### ISSUE TITLE
audio_spdif.c line 203, gibe --> give?

### ISSUE THREAD

**Issue by NorioFujii** [raspberrypi/pico-extras#9]
Tested by only PICO_AUDIO_SPDIF_MONO_INPUT=1 mode.

**Comment by lurch** [comment]
Yeah, looks like a simple typo, thanks. The function-definition is here https://github.com/raspberrypi/pico-extras/blob/master/src/rp2_common/pico_audio_spdif/include/pico/audio_spdif/sample_encoding.h#L17
